from typing import Any, Protocol

from ..models import ChatMessage, RelayRecord


class Storage(Protocol):
    async def add_message(self, message: ChatMessage, keep: int) -> None: ...

    async def recent_messages(self, limit: int) -> list[ChatMessage]: ...

    # Засчитать событие. Лимит выбран — ничего не пишет и возвращает, через сколько секунд можно.
    async def hit(self, key: str, window: float, limit: int, now: float) -> float | None: ...

    async def ban(self, subject: str, until: float | None) -> None: ...

    async def unban(self, subject: str) -> None: ...

    async def banned(self, subjects: list[str], now: float) -> bool: ...

    async def set_site_mute(self, until: float | None) -> None: ...

    async def site_mute_until(self, now: float) -> float | None: ...

    async def put_challenge(self, challenge_id: str, data: dict[str, Any], ttl: int) -> None: ...

    async def take_challenge(self, challenge_id: str) -> dict[str, Any] | None: ...

    async def remember_relay(self, tg_message_id: int, record: RelayRecord, ttl: int) -> None: ...

    async def relay(self, tg_message_id: int) -> RelayRecord | None: ...

    async def close(self) -> None: ...
